factorial function has been completed
js-tasks-ru/jsbasic-20210621_konstantin-kh pull request #3
Opened 2021-06-28 13:15 UTC by konstantin-kh

1-module\1-task - factorial function has been completed

2021-06-28 13:16 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-28 15:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-06-28 16:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-06-28 17:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-06-28 19:09 UTC, SinimaWath requested changes

2021-06-28 19:09 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    }
это условие можны вынести за цикл, что бы зря его не начинать

2021-06-28 19:09 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  if (name === null || name.length < 4 || ~name.indexOf(' ')) {
Давай заменим indexOf на includes

2021-06-28 19:09 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if (~str.indexOf(' ') !== -1) {
на includes давай поменяем. И у тебя потерялось условие else

2021-06-28 19:09 UTC, SinimaWath commented on 1-module/4-task/index.js
> +    }
можно неписать continue,  код и так продолжит исполняться

2021-06-28 19:09 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let lowerStr = str.toLowerCase();
Кажется это const

2021-06-29 12:36 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-29 15:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-06-29 15:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-06-29 20:54 UTC, SinimaWath approved these changes

2021-06-29 20:55 UTC, merged