added 3 tasks from topic "Functions and Arrays"
js-tasks-ru/jsbasic-20210621_konstantin-kh pull request #5
Opened 2021-07-08 16:06 UTC by konstantin-kh

1. namify
2. filterRange
3. camelize

2021-07-08 16:07 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-09 10:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-10 15:45 UTC, SinimaWath requested changes

2021-07-10 15:45 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names;
Давай тут используем map

2021-07-10 15:45 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return found;
Давай используем filter->map

2021-07-10 15:45 UTC, SinimaWath commented on 3-module/3-task/index.js
> +    if (elem.includes("-")) {
Это немного лишняя проверка.

Можно проверить, используя только index. index === 0 - в этом случае не нужно делать toUpperCase

2021-07-10 15:45 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  arr.forEach((elem, i) => {
Давай тут тоже map используем

2021-07-13 21:04 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-13 21:29 UTC, SinimaWath requested changes

2021-07-13 21:29 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  });
map - специальная метод, он заменяет елементы в массиве.

Поэтому требуется, чтобы функция, которую ты передал, возвращала новое значение.

То есть тебе не надо изменять массив arr[i], тебе надо просто вернуть новое значение из функции

2021-07-13 21:29 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return res = arr.join('');
return res = arr.join('') - не нужно присваивать значение переменной, если ты уже возвращаешь значение.

`return arr.join('')`

2021-07-13 21:29 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  });
Эту запист можно заменить на: `filter->map`.

2021-07-13 21:29 UTC, SinimaWath commented on 3-module/4-task/index.js
> +        list += `${elem}\n`;
для того чтобы добавить `\n` используй join('\n')

2021-07-17 14:48 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-17 19:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-17 19:33 UTC, SinimaWath approved these changes

2021-07-17 19:34 UTC, merged