added makeDiagonalRed
js-tasks-ru/jsbasic-20210621_konstantin-kh pull request #6
Opened 2021-07-17 20:28 UTC by konstantin-kh

4-module

2021-07-17 20:29 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-18 14:01 UTC, SinimaWath requested changes

2021-07-18 14:01 UTC, SinimaWath commented on 4-module/2-task/index.js
> +    for (let j in row.cells) {
Давай попробуем через один for. Так как по условию задачи это диагональ - это позволяет использовать только один for.

2021-07-18 18:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-19 13:08 UTC, SinimaWath approved these changes

2021-07-19 13:08 UTC, merged